//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoenaSoft.DVDProfiler.CastCrewEdit2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EditWindowNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditWindowNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoenaSoft.DVDProfiler.CastCrewEdit2.Resources.EditWindowNames", typeof(EditWindowNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Config File &quot;{0}&quot;.
        /// </summary>
        internal static string EditConfigFile {
            get {
                return ResourceManager.GetString("EditConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore &quot;Custom&quot; in IMDb Category.
        /// </summary>
        internal static string IgnoreCustominIMDbCategory {
            get {
                return ResourceManager.GetString("IgnoreCustominIMDbCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore IMDb Category in &quot;Other&quot;.
        /// </summary>
        internal static string IgnoreIMDbCategoryinOther {
            get {
                return ResourceManager.GetString("IgnoreIMDbCategoryinOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname Prefixes.
        /// </summary>
        internal static string KnownFirstnamePrefixes {
            get {
                return ResourceManager.GetString("KnownFirstnamePrefixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname Prefixes.
        /// </summary>
        internal static string KnownLastnamePrefixes {
            get {
                return ResourceManager.GetString("KnownLastnamePrefixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname Suffixes.
        /// </summary>
        internal static string KnownLastnameSuffixes {
            get {
                return ResourceManager.GetString("KnownLastnameSuffixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known Names.
        /// </summary>
        internal static string KnownNames {
            get {
                return ResourceManager.GetString("KnownNames", resourceCulture);
            }
        }
    }
}
