//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoenaSoft.DVDProfiler.CastCrewEdit2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageBoxTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageBoxTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoenaSoft.DVDProfiler.CastCrewEdit2.Resources.MessageBoxTexts", typeof(MessageBoxTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s already an instance running. If you start another one, you could invalidate your cache. Continue?.
        /// </summary>
        internal static string AnotherInstanceRunning {
            get {
                return ResourceManager.GetString("AnotherInstanceRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth year of cast member &quot;{0}&quot; ({3}) has changed.
        ///Old: {1}
        ///New: {2}
        ///Check your DVD Profiler for consistency..
        /// </summary>
        internal static string BirthYearCastHasChanged {
            get {
                return ResourceManager.GetString("BirthYearCastHasChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth year of crew member &quot;{0}&quot; ({3}) has changed.
        ///Old: {1}
        ///New: {2}
        ///Check your DVD Profiler for consistency..
        /// </summary>
        internal static string BirthYearCrewHasChanged {
            get {
                return ResourceManager.GetString("BirthYearCrewHasChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data successfully copied to Clipboard. You can now open the Cast Edit Screen in DVD Profiler and paste the data into it..
        /// </summary>
        internal static string CastDataCopySuccessful {
            get {
                return ResourceManager.GetString("CastDataCopySuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common name of cast member &quot;{0}&quot; ({3}) has changed.
        ///Old: {1}
        ///New: {2}
        ///Check your DVD Profiler for consistency..
        /// </summary>
        internal static string CommonCastNameHasChanged {
            get {
                return ResourceManager.GetString("CommonCastNameHasChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common name of crew member &quot;{0}&quot; ({3}) has changed.
        ///Old: {1}
        ///New: {2}
        ///Check your DVD Profiler for consistency..
        /// </summary>
        internal static string CommonCrewNameHasChanged {
            get {
                return ResourceManager.GetString("CommonCrewNameHasChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue?.
        /// </summary>
        internal static string ContinueHeader {
            get {
                return ResourceManager.GetString("ContinueHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying data to the Clipboard has failed. Please try again..
        /// </summary>
        internal static string CopyToClipboardFailed {
            get {
                return ResourceManager.GetString("CopyToClipboardFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data successfully copied to Clipboard. You can now open the Crew Edit Screen in DVD Profiler and paste the data into it..
        /// </summary>
        internal static string CrewDataCopySuccessful {
            get {
                return ResourceManager.GetString("CrewDataCopySuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///
        ///A log file was created under &quot;{1}&quot;. Please send it to karsten@yajirobi.de..
        /// </summary>
        internal static string CriticalError {
            get {
                return ResourceManager.GetString("CriticalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Error!.
        /// </summary>
        internal static string CriticalErrorHeader {
            get {
                return ResourceManager.GetString("CriticalErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying Successful..
        /// </summary>
        internal static string DataCopySuccessfulHeader {
            get {
                return ResourceManager.GetString("DataCopySuccessfulHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must not contribute IMDb data to the DVD Profiler Online Database. Do you understand?.
        /// </summary>
        internal static string DontContributeIMDbData {
            get {
                return ResourceManager.GetString("DontContributeIMDbData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do NOT contribute IMDb data!.
        /// </summary>
        internal static string DontContributeIMDbDataHeader {
            get {
                return ResourceManager.GetString("DontContributeIMDbDataHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the same full name twice!.
        /// </summary>
        internal static string DuplicateFullName {
            get {
                return ResourceManager.GetString("DuplicateFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A first name field is empty!.
        /// </summary>
        internal static string EmptyFirstName {
            get {
                return ResourceManager.GetString("EmptyFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A full name field is empty!.
        /// </summary>
        internal static string EmptyFullName {
            get {
                return ResourceManager.GetString("EmptyFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Webserver has blocked further requests.
        ///Please press the &quot;{0}&quot; button until the program tells you that the parsing is complete..
        /// </summary>
        internal static string Error503 {
            get {
                return ResourceManager.GetString("Error503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string ErrorHeader {
            get {
                return ResourceManager.GetString("ErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to this actor&apos;s IMDb of {0}, he has gotten an empty fake birth year assigned.
        ///
        ///{1}.
        /// </summary>
        internal static string FakeBirthYearZeroCast {
            get {
                return ResourceManager.GetString("FakeBirthYearZeroCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to this crew member&apos;s IMDb of {0}, he has gotten an empty fake birth year assigned.
        ///
        ///{1}.
        /// </summary>
        internal static string FakeBirthYearZeroCrew {
            get {
                return ResourceManager.GetString("FakeBirthYearZeroCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; can&apos;t be read..
        /// </summary>
        internal static string FileCantBeRead {
            get {
                return ResourceManager.GetString("FileCantBeRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; can&apos;t be written..
        /// </summary>
        internal static string FileCantBeWritten {
            get {
                return ResourceManager.GetString("FileCantBeWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; does not exist..
        /// </summary>
        internal static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The files will now be moved. Existing files in the target directory will be removed. Continue?.
        /// </summary>
        internal static string FilesWillNowBeMoved {
            get {
                return ResourceManager.GetString("FilesWillNowBeMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target folder for the headshots is invalid. Please check the folder in DVDProfiler -&gt; Tools -&gt; Options -&gt; File Folders -&gt; Credit Photos..
        /// </summary>
        internal static string HeadShotsTargetDirectoryInvalid {
            get {
                return ResourceManager.GetString("HeadShotsTargetDirectoryInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Photos Folder is Invalid!.
        /// </summary>
        internal static string HeadShotsTargetDirectoryInvalidHeader {
            get {
                return ResourceManager.GetString("HeadShotsTargetDirectoryInvalidHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These people have gotten fake birth years assigned. Make sure that you have different entries for these people in DVDProfiler before you paste the data.
        ///{0}.
        /// </summary>
        internal static string NewFakeBirthYears {
            get {
                return ResourceManager.GetString("NewFakeBirthYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one episode..
        /// </summary>
        internal static string NoEpisodeSelected {
            get {
                return ResourceManager.GetString("NoEpisodeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Episode Selected!.
        /// </summary>
        internal static string NoEpisodeSelectedHeader {
            get {
                return ResourceManager.GetString("NoEpisodeSelectedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No episodes have been found. Please re-scan the page..
        /// </summary>
        internal static string NoEpisodesFound {
            get {
                return ResourceManager.GetString("NoEpisodesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episode List is Missing!.
        /// </summary>
        internal static string NoEpisodesFoundHeader {
            get {
                return ResourceManager.GetString("NoEpisodesFoundHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one season..
        /// </summary>
        internal static string NoSeasonSelected {
            get {
                return ResourceManager.GetString("NoSeasonSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Season Selected!.
        /// </summary>
        internal static string NoSeasonSelectedHeader {
            get {
                return ResourceManager.GetString("NoSeasonSelectedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing Complete..
        /// </summary>
        internal static string ParsingComplete {
            get {
                return ResourceManager.GetString("ParsingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the same name with and without a birth year. Make sure that you have different entries for these people in DVDProfiler before you paste the data.
        ///{0}.
        /// </summary>
        internal static string PossibleDuplicates {
            get {
                return ResourceManager.GetString("PossibleDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the same name with the same birth year multiple times. At this point there&apos;s nothing we can do about that - but be aware of the fact.
        ///{0}.
        /// </summary>
        internal static string PossibleSameYearDuplicates {
            get {
                return ResourceManager.GetString("PossibleSameYearDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Data?.
        /// </summary>
        internal static string SaveData {
            get {
                return ResourceManager.GetString("SaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before running this new version, you have to update the Persons.xml first.
        ///Please read the Versions Hints of the readme.html and run
        ///ConvertCastCrewEdit2PersonFile.exe..
        /// </summary>
        internal static string UpdatePersonsXml {
            get {
                return ResourceManager.GetString("UpdatePersonsXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL is empty!.
        /// </summary>
        internal static string UrlIsEmpty {
            get {
                return ResourceManager.GetString("UrlIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty URL!.
        /// </summary>
        internal static string UrlIsEmptyHeader {
            get {
                return ResourceManager.GetString("UrlIsEmptyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL is incorrect! Please use an URL of the form http://www.imdb.com/title/tt0000000/..
        /// </summary>
        internal static string UrlIsIncorrect {
            get {
                return ResourceManager.GetString("UrlIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect URL!.
        /// </summary>
        internal static string UrlIsIncorrectHeader {
            get {
                return ResourceManager.GetString("UrlIsIncorrectHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string WarningHeader {
            get {
                return ResourceManager.GetString("WarningHeader", resourceCulture);
            }
        }
    }
}
